title: Doc Test
permalink: /:slug/
collections:
  docs:
    output: true
    permalink: /:slug/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: page
      comments: true
